/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnfragenRouteImport } from './routes/anfragen'
import { Route as InfoRouteImport } from './routes/info'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BilderFileRouteImport } from './routes/bilder.$file'
import { Route as KrabiGuideIndexRouteImport } from './routes/krabi-guide.index'
import { Route as KrabiGuideSlugRouteImport } from './routes/krabi-guide.$slug'
import { Route as SecretIslandsSplatRouteImport } from './routes/secret-islands.$'
import { Route as TourenIndexRouteImport } from './routes/touren.index'
import { Route as TourenSlugRouteImport } from './routes/touren.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnfragenRoute = AnfragenRouteImport.update({
  id: '/anfragen',
  path: '/anfragen',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BilderFileRoute = BilderFileRouteImport.update({
  id: '/bilder/$file',
  path: '/bilder/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const KrabiGuideIndexRoute = KrabiGuideIndexRouteImport.update({
  id: '/krabi-guide/',
  path: '/krabi-guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const KrabiGuideSlugRoute = KrabiGuideSlugRouteImport.update({
  id: '/krabi-guide/$slug',
  path: '/krabi-guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretIslandsSplatRoute = SecretIslandsSplatRouteImport.update({
  id: '/secret-islands/$',
  path: '/secret-islands/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TourenIndexRoute = TourenIndexRouteImport.update({
  id: '/touren/',
  path: '/touren/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourenSlugRoute = TourenSlugRouteImport.update({
  id: '/touren/$slug',
  path: '/touren/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anfragen': typeof AnfragenRoute
  '/info': typeof InfoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bilder/$file': typeof BilderFileRoute
  '/krabi-guide/$slug': typeof KrabiGuideSlugRoute
  '/secret-islands/$': typeof SecretIslandsSplatRoute
  '/touren/$slug': typeof TourenSlugRoute
  '/krabi-guide/': typeof KrabiGuideIndexRoute
  '/touren/': typeof TourenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anfragen': typeof AnfragenRoute
  '/info': typeof InfoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bilder/$file': typeof BilderFileRoute
  '/krabi-guide/$slug': typeof KrabiGuideSlugRoute
  '/secret-islands/$': typeof SecretIslandsSplatRoute
  '/touren/$slug': typeof TourenSlugRoute
  '/krabi-guide': typeof KrabiGuideIndexRoute
  '/touren': typeof TourenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anfragen': typeof AnfragenRoute
  '/info': typeof InfoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bilder/$file': typeof BilderFileRoute
  '/krabi-guide/$slug': typeof KrabiGuideSlugRoute
  '/secret-islands/$': typeof SecretIslandsSplatRoute
  '/touren/$slug': typeof TourenSlugRoute
  '/krabi-guide/': typeof KrabiGuideIndexRoute
  '/touren/': typeof TourenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anfragen'
    | '/info'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/bilder/$file'
    | '/krabi-guide/$slug'
    | '/secret-islands/$'
    | '/touren/$slug'
    | '/krabi-guide/'
    | '/touren/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anfragen'
    | '/info'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/bilder/$file'
    | '/krabi-guide/$slug'
    | '/secret-islands/$'
    | '/touren/$slug'
    | '/krabi-guide'
    | '/touren'
  id:
    | '__root__'
    | '/'
    | '/anfragen'
    | '/info'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/bilder/$file'
    | '/krabi-guide/$slug'
    | '/secret-islands/$'
    | '/touren/$slug'
    | '/krabi-guide/'
    | '/touren/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnfragenRoute: typeof AnfragenRoute
  InfoRoute: typeof InfoRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BilderFileRoute: typeof BilderFileRoute
  KrabiGuideSlugRoute: typeof KrabiGuideSlugRoute
  SecretIslandsSplatRoute: typeof SecretIslandsSplatRoute
  TourenSlugRoute: typeof TourenSlugRoute
  KrabiGuideIndexRoute: typeof KrabiGuideIndexRoute
  TourenIndexRoute: typeof TourenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anfragen': {
      id: '/anfragen'
      path: '/anfragen'
      fullPath: '/anfragen'
      preLoaderRoute: typeof AnfragenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilder/$file': {
      id: '/bilder/$file'
      path: '/bilder/$file'
      fullPath: '/bilder/$file'
      preLoaderRoute: typeof BilderFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krabi-guide/': {
      id: '/krabi-guide/'
      path: '/krabi-guide'
      fullPath: '/krabi-guide/'
      preLoaderRoute: typeof KrabiGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krabi-guide/$slug': {
      id: '/krabi-guide/$slug'
      path: '/krabi-guide/$slug'
      fullPath: '/krabi-guide/$slug'
      preLoaderRoute: typeof KrabiGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret-islands/$': {
      id: '/secret-islands/$'
      path: '/secret-islands/$'
      fullPath: '/secret-islands/$'
      preLoaderRoute: typeof SecretIslandsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/touren/': {
      id: '/touren/'
      path: '/touren'
      fullPath: '/touren/'
      preLoaderRoute: typeof TourenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/touren/$slug': {
      id: '/touren/$slug'
      path: '/touren/$slug'
      fullPath: '/touren/$slug'
      preLoaderRoute: typeof TourenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnfragenRoute: AnfragenRoute,
  InfoRoute: InfoRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BilderFileRoute: BilderFileRoute,
  KrabiGuideSlugRoute: KrabiGuideSlugRoute,
  SecretIslandsSplatRoute: SecretIslandsSplatRoute,
  TourenSlugRoute: TourenSlugRoute,
  KrabiGuideIndexRoute: KrabiGuideIndexRoute,
  TourenIndexRoute: TourenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
